version: "3.5"

services:
  nginx:
    image: nginx:1.27.4-alpine
    container_name: card_payment_service_nginx
    volumes:
      - ./:/var/task
      - ./docker/nginx/:/etc/nginx/conf.d/
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - php_fpm
    networks:
      - card_payment_service

  php_fpm:
    container_name: card_payment_service_php_fpm
    build:
      context: ./docker/php_fpm
    volumes:
      - ./:/var/task
    working_dir: /var/task
    networks:
      - card_payment_service

networks:
  card_payment_service:
